### ISSUE TITLE
[BUG]: UI is different from the screenshot

### ISSUE THREAD

**Issue by ogirginc** [2KAbhishek/co-author.nvim#1]
### Description of the bug

This is what I see:

<img width="702" alt="Screenshot 2023-01-23 at 13 19 04" src="https://user-images.githubusercontent.com/7466873/214016218-111ef502-2523-4496-a769-416681adb0e0.png">

### Steps To Reproduce

1. `git add .`
2. `git commit`
3. `: GitCoAuthors`
4. See the list in a terminal pager

### Additional Information

Do I need a plug-in to make it look like the screenshot?

**Comment by 2KAbhishek** [comment]
Yes, you'll need two different plugins to make the select UI look and function like that.

- [dressing.nvim](https://github.com/stevearc/dressing.nvim) — for prettier select UI
- [telescope](https://github.com/nvim-telescope/telescope.nvim) — for fuzzy searching in list

Installing them should do the trick.
Thanks a lot for raising the issue, it was an overlook on my part

P.S: If you found the plugin useful, do drop a ⭐ that motivates me a lot!

**Comment by 2KAbhishek** [comment]
I have also updated the README so new users won't have problems

**Comment by ogirginc** [comment]
I can confirm it works as expected after installing `dressing.nvim` as I already had `telescope`. 

Also, thanks for the fast reply. 👏
