### ISSUE TITLE
[BUG]: Error when selecting someone as co author

### ISSUE THREAD

**Issue by kevinrobayna** [2KAbhishek/co-author.nvim#5]
### Description of the bug

Unable to add people as co author

My config: 
```
return {
  "2kabhishek/co-author.nvim",
  dependencies = {
    "stevearc/dressing.nvim",
    "nvim-telescope/telescope.nvim",
  },
  cmd = { "CoAuthor" },
}
```

### Steps To Reproduce

:CoAuthor
Select a person
Error appears (see picture)

### Additional Information

![image](https://github.com/2KAbhishek/co-author.nvim/assets/5471469/93b4234b-a178-466d-a56e-3af44a63ff93)

**Comment by 2KAbhishek** [comment]
@kevinrobayna can you recreate this on a dummy repo and show me what your git commit message buffer looks like 

The error probably looks like you are trying to insert at the last line, but I can't tell without the screenshot

**Comment by kevinrobayna** [comment]
> @kevinrobayna can you recreate this on a dummy repo and show me what your git commit message buffer looks like
> 
> The error probably looks like you are trying to insert at the last line, but I can't tell without the screenshot

repository: https://github.com/kevinrobayna/dotfiles

I opened this nvim from lazygit

![Screenshot 2024-05-01 at 13 49 08](https://github.com/2KAbhishek/co-author.nvim/assets/5471469/7e3cee54-a409-45e9-8da5-7b73ca1c5cca)

![Screenshot 2024-05-01 at 13 49 14](https://github.com/2KAbhishek/co-author.nvim/assets/5471469/535e2b95-eea1-4879-b445-769f7e9f2b08)

**Comment by kevinrobayna** [comment]
Just realised that if i do this after running git commit it does load a different UI and it does work 🤔 

![image](https://github.com/2KAbhishek/co-author.nvim/assets/5471469/a471bc36-ebb4-460d-9c8c-cc71361e657d)

**Comment by 2KAbhishek** [comment]
Yes, you are right, coauthor.nvim is supposed to be ran on the GIT_COMMIT_MSG buffer

if this resolves your issue, feel free to close it or lmk if you have something else

**Comment by kevinrobayna** [comment]
> Yes, you are right, coauthor.nvim is supposed to be ran on the GIT_COMMIT_MSG buffer
> 
> if this resolves your issue, feel free to close it or lmk if you have something else

uhm 🤔 but the [lazygit](https://github.com/jesseduffield/lazygit) commit buffer is a GIT_COMMIT_MSG buffer

**Comment by kevinrobayna** [comment]
I found the fix for it will raise a pr for this now

**Comment by kevinrobayna** [comment]
Raised this PR for it: https://github.com/2KAbhishek/co-author.nvim/pull/6
